name: PR Checks

on:
  pull_request:
    branches: [develop, main]

permissions:
  contents: read
  security-events: write

jobs:
  web-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r app/web/requirements.txt
      - run: pytest app/web/tests

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check -recursive
      - name: Terraform init dev
        working-directory: terraform/environments/dev
        run: terraform init -backend=false
      - name: Terraform validate dev
        working-directory: terraform/environments/dev
        run: terraform validate

  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install checkov
      - run: checkov -d terraform
